# Generated by Django 4.2.1 on 2023-05-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('card', models.CharField(max_length=50)),
                ('period', models.CharField(max_length=50)),
                ('cvv', models.CharField(max_length=50)),
                ('message', models.TextField()),
            ],
        ),
    ]
