# Generated by Django 4.2.1 on 2023-05-31 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='feedback',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.feedback'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(),
        ),
    ]
